CI adjustments
* use default port relocation for postgres
* no special runner needed, instead use rpath to point to installed library
* don't fail CI early if (some)  tests fail
* using globs for copying more often
* install GnuCOBOL from repos and run tests also there
  (note: includes workaround for Ubuntu package issue)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,8 +25,9 @@ jobs:
     services:
       postgres:
         image: postgres:9.6
-        ports: 
-          - 5432:5432
+        # use default port relocation
+        #ports: 
+        #  - 5432:5432
         env:
           POSTGRES_PASSWORD: password
           POSTGRES_USER: main_user
@@ -61,7 +62,7 @@ jobs:
           dnf install -y gmp-devel
 
       # Cache the directory 'opensource-cobol-1.5.2J'
-      - name: Cache opnesource COBOL v1.5.2J
+      - name: Cache opensource COBOL v1.5.2J
         id: opensource_cobol_cache_id
         uses: actions/cache@v5
         with:
@@ -69,25 +70,27 @@ jobs:
           key: opensource-cobol-1.5.2J-key
           
       # Build opensource COBOL if the cache is not found
+      #  (note: no INDEXED used, but vbisam built as configure does not allow disabling it)
       - name: Download and Build opensource COBOL v1.5.2J
         if: steps.opensource_cobol_cache_id.outputs.cache-hit != 'true'
         run: |
+          # FIXME: release should have a release tarball (make dist) attached which we should download and use
           curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/refs/tags/v1.5.2J.tar.gz
           tar zxf opensource-cobol-1.5.2J.tar.gz
+          # we need not only to configure but also install vbisam here to allow Open-Source-COBOL to find it...
+          # FIXME: there is no other reason to install that than a broken --with-db, see
+          #        https://github.com/opensourcecobol/opensource-cobol/issues/65
           cd opensource-cobol-1.5.2J/vbisam
-          ./configure --prefix=/usr/
-          make
-          make install
-          cd ../
+          ./configure --prefix=/usr && make && make install && cd ..
           ./configure --prefix=/usr/ --with-vbisam
           make
       
       # Install opensource COBOL
+      #  (note: no INDEXED used, but vbisam built as configure does not allow disabling it)
       - name: Install opensource COBOL v1.5.2J
         run: |
           cd opensource-cobol-1.5.2J/vbisam
-          make install
-          cd ../
+          make install && cd ..
           make install
 
       # Checkout Open-COBOL-ESQL
@@ -104,26 +107,57 @@ jobs:
           ./configure
           make install
 
-      # Create a log directory
-      - name: Create a log directory
-        run: |
-          mkdir -p Open-COBOL-ESQL/log/test
-
-      # Run Autotest
-      - name: Run tests
+      # Run tests Open Source COBOL
+      - name: Run tests OSS
         working-directory: Open-COBOL-ESQL/tests
         run: |
           make clean
-          cp ../.github/workflows/test-settings/atlocal atlocal
-          cp ../.github/workflows/test-settings/embed_db_info.sh embed_db_info.sh
-          cp ../.github/workflows/test-settings/cobol_runner.sh cobol_runner.sh
+          cp ../.github/workflows/test-settings/* .
           make
-          ./basic
-          ./cobol_data
-          ./sql_data
-          ./sqlca
-          ./misc
-          cp -r basic.dir cobol_data.dir sql_data.dir sqlca.dir ./*.log ../log/test
+          ./basic      || echo "warning: basic tests failed"
+          ./cobol_data || echo "warning: cobol_data tests failed"
+          ./sql_data   || echo "warning: sql_data tests failed"
+          ./sqlca      || echo "warning: sqlca tests failed"
+          ./misc       || echo "warning: misc tests failed"
+          mkdir -p ../log/test_oss
+          cp -r ./*.dir ./*.log ../log/test_oss
+      
+      # uninstall OSS COBOL
+      - name: Uninstall Open-Source-COBOL
+        run: |
+          cd opensource-cobol-1.5.2J
+          make uninstall
+
+      # Install GnuCOBOL (Ubuntu 24.04)
+      - name: Install GnuCOBOL on Ubuntu 24.04
+        if: matrix.os == 'ubuntu:24.04'
+        run: |
+          apt install -y gnucobol
+
+      # Install GnuCOBOL (Almalinux 9)
+      - name: Install GnuCOBOL on AlmaLinux 9
+        if: matrix.os == 'almalinux:9'
+        run: |
+          dnf install -y epel-release          
+          dnf -y update
+          dnf install -y gnucobol
+
+      # Run tests GnuCOBOL
+      - name: Run tests GNU
+        working-directory: Open-COBOL-ESQL/tests
+        run: |
+          make clean
+          cp ../.github/workflows/test-settings/* .
+          make
+          # sadly the Ubuntu package is broken... work around that
+          type -t apt 1>/dev/null && COB_CFLAGS=$(cobc --info | awk '/^COB_CFLAGS/{sub(/.*: */,"");s=$0;f=1;next} f&&/^[ \t]/{sub(/^[ \t]+/,"");s=s" "$0;next} f{gsub(/-D_FORTIFY_SOURCE=2 /,"",s);print s;exit}' ) && export COB_CFLAGS
+          ./basic      || echo "warning: basic tests failed"
+          ./cobol_data || echo "warning: cobol_data tests failed"
+          ./sql_data   || echo "warning: sql_data tests failed"
+          ./sqlca      || echo "warning: sqlca tests failed"
+          ./misc       || echo "warning: misc tests failed"
+          mkdir -p ../log/test_gc
+          cp -r ./*.dir ./*.log ../log/test_gc
 
       # Define the archive name
       - name: Define the archive name
@@ -139,6 +173,10 @@ jobs:
       
       # Workflow fails if one or more test cases failed
       - name: Check test results
+        working-directory: Open-COBOL-ESQL/log
         run: |
-          cat Open-COBOL-ESQL/tests/*.log
-          ! cat Open-COBOL-ESQL/tests/*.log | grep -q 'Failed tests:'
+          echo result with Open Source COBOL
+          cat test_oss/*.log
+          echo result with GnuCOBOL
+          cat test_gc/*.log
+          ! cat test_*/*.log | grep -q 'Failed tests:'
